### PR TITLE
Run and add ssh key to agent

### LINKED ISSUE #4: Add the new key to the ssh-agent
After the key is generated, automatically add it to the ssh-agent by `ssh-add ~/.ssh/cscs-key`. 
At the moment, I have to edit the `~/.ssh/config` to point to the `cscs-key`. If the ssh-agent contain the key, then the ssh-config file can kept simple and works charm with the new `ComputationalResourceWidget`.

### PR DESCRIPTION
**Pull request by unkcpz**
fixes #4

### CODE REVIEW

**Comment by unkcpz** [comment]
If you test with latest full-stack docker image, after generating the key pairs and the `ssh-add` runs to add to agent. You may still not able to see the key added with `ssh-add -l` when you open a new terminal app. The reason is there are two ssh-agent running. This is another thing we need to address by https://github.com/aiidalab/aiidalab-docker-stack/pull/409. Only one ssh-agent will run on the session and as mentioned by @danielhollas, it may not be a good idea to put script in `.bashrc`.
But for this PR, I think it is ready, if you make sure there is only one ssh-agent, after generating the keys, you can find it also added to the  agent.

**Comment by danielhollas** [comment]
> The reason is there are two ssh-agent running. 

I don't understand. How is it possible that two `ssh-agents` are running? I thought that the script that we use should ensure that only one ssh-agent is running.

**Comment by unkcpz** [comment]
> I don't understand. How is it possible that two ssh-agents are running?

I have no idea, to be honest. The good thing is I can reproduce it with `full-stack`. Let's try to merge https://github.com/aiidalab/aiidalab-docker-stack/pull/409 first and see if the problem disappears. At least, I think your change there makes things more clear. Hope we can find the problem if it is still exist.

**Comment by unkcpz** [comment]
This is tested with the newly released docker stack (I use `ghcr.io/aiidalab/qe:edge`) and the key is successfully added to ssh-agent. 
@yakutovicha Can you have a look and test it? After this change, the computational resource widget can work with this mfa-cscs seamlessly.

**Comment by yakutovicha** [comment]
> This is tested with the newly released docker stack (I use `ghcr.io/aiidalab/qe:edge`) and the key is successfully added to ssh-agent. @yakutovicha Can you have a look and test it? After this change, the computational resource widget can work with this mfa-cscs seamlessly.

Sorry, @unkcpz,  I am on it now.

**Review by yakutovicha — APPROVED** [review]
I tested things locally, it is all good 👍

**Comment by unkcpz** [comment]
Cool, thanks! Then I'll prepare a release and put the app on the app store, is that okay for you?

**Comment by yakutovicha** [comment]
> Cool, thanks! Then I'll prepare a release and put the app on the app store, is that okay for you?

Yep, please go ahead, thanks!

**Pull request merged**
